#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UpgradeApp.Resource", IsApplication=true)]

namespace UpgradeApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int upgradeLogo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050013
			public const int AboutEditText = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int AboutLabelTextView = 2131034130;
			
			// aapt resource value: 0x7f050036
			public const int AboutTextView = 2131034166;
			
			// aapt resource value: 0x7f05003d
			public const int AvailabilityLabelTextView = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int AvailabilityTextView = 2131034174;
			
			// aapt resource value: 0x7f050029
			public const int AvatarImageView = 2131034153;
			
			// aapt resource value: 0x7f050031
			public const int BlockButton = 2131034161;
			
			// aapt resource value: 0x7f05000f
			public const int ContactLabelTextView = 2131034127;
			
			// aapt resource value: 0x7f05002c
			public const int ContactMethodsLabelTextView = 2131034156;
			
			// aapt resource value: 0x7f05002e
			public const int ContactMethodsTextView = 2131034158;
			
			// aapt resource value: 0x7f050030
			public const int EditButton = 2131034160;
			
			// aapt resource value: 0x7f050010
			public const int EmailEditText = 2131034128;
			
			// aapt resource value: 0x7f05002d
			public const int EmailTextView = 2131034157;
			
			// aapt resource value: 0x7f050017
			public const int FreeTimeEditText = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int FreeTimeLabelTextView = 2131034134;
			
			// aapt resource value: 0x7f05003b
			public const int INeedATutorLabelTextView = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int INeedATutorTextView = 2131034172;
			
			// aapt resource value: 0x7f050014
			public const int ITutorLabelTextView = 2131034132;
			
			// aapt resource value: 0x7f050039
			public const int ITutorTextView = 2131034169;
			
			// aapt resource value: 0x7f050015
			public const int IWantToStudyTextView = 2131034133;
			
			// aapt resource value: 0x7f05000e
			public const int NameEditText = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int NameLabelTextView = 2131034125;
			
			// aapt resource value: 0x7f050028
			public const int NameTextView = 2131034152;
			
			// aapt resource value: 0x7f050011
			public const int OtherContactMethodsEditText = 2131034129;
			
			// aapt resource value: 0x7f050019
			public const int PricesEditText = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int PricesLabelTextView = 2131034136;
			
			// aapt resource value: 0x7f05003f
			public const int PricesTextView = 2131034175;
			
			// aapt resource value: 0x7f050035
			public const int RateButton = 2131034165;
			
			// aapt resource value: 0x7f050034
			public const int RatingTextView = 2131034164;
			
			// aapt resource value: 0x7f050026
			public const int RecoveryQuestion = 2131034150;
			
			// aapt resource value: 0x7f050032
			public const int ReportButton = 2131034162;
			
			// aapt resource value: 0x7f05002b
			public const int SendMessageButton = 2131034155;
			
			// aapt resource value: 0x7f05001a
			public const int SubmitButton = 2131034138;
			
			// aapt resource value: 0x7f05000a
			public const int bubble_layout = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int bubble_layout_parent = 2131034121;
			
			// aapt resource value: 0x7f050040
			public const int classButton = 2131034176;
			
			// aapt resource value: 0x7f05000c
			public const int classList = 2131034124;
			
			// aapt resource value: 0x7f05001d
			public const int createAccountButton = 2131034141;
			
			// aapt resource value: 0x7f050003
			public const int email = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int emailHelper = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int firstAndLast = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int firstName = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int lastName = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f05002a
			public const int linearLayout2 = 2131034154;
			
			// aapt resource value: 0x7f050037
			public const int linearLayout3 = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int linearLayout4 = 2131034168;
			
			// aapt resource value: 0x7f05003a
			public const int linearLayout5 = 2131034170;
			
			// aapt resource value: 0x7f05002f
			public const int linearLayout6 = 2131034159;
			
			// aapt resource value: 0x7f050033
			public const int linearLayout7 = 2131034163;
			
			// aapt resource value: 0x7f05001c
			public const int loginButton = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int message = 2131034143;
			
			// aapt resource value: 0x7f05000b
			public const int message_text = 2131034123;
			
			// aapt resource value: 0x7f050020
			public const int msg = 2131034144;
			
			// aapt resource value: 0x7f050004
			public const int password = 2131034116;
			
			// aapt resource value: 0x7f050027
			public const int recoverAnswer = 2131034151;
			
			// aapt resource value: 0x7f05001e
			public const int recoverButton = 2131034142;
			
			// aapt resource value: 0x7f050023
			public const int recoverQuestion = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int recoveryAnswer = 2131034148;
			
			// aapt resource value: 0x7f050021
			public const int send = 2131034145;
			
			// aapt resource value: 0x7f05001b
			public const int students = 2131034139;
			
			// aapt resource value: 0x7f050008
			public const int submitButton = 2131034120;
			
			// aapt resource value: 0x7f050025
			public const int text1 = 2131034149;
			
			// aapt resource value: 0x7f050022
			public const int textView1 = 2131034146;
			
			// aapt resource value: 0x7f050001
			public const int upgradeLogo = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AccountCreationScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int bubbler = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ClassesScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditProfileScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int listOfStudents = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int messaging = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PasswordRecoverySet = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PasswordRecoveryUseScreen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ProfileScreen = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
